'use client'

import { useEffect, useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Camera, CheckCircle2, AlertCircle, QrCode, Search, Loader2 } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

type ScanStatus = 'idle' | 'scanning' | 'found' | 'not-found' | 'error'

export default function QRScannerClient() {
  const router = useRouter()
  const scannerInstance = useRef<any>(null)
  const [status, setStatus] = useState<ScanStatus>('idle')
  const [scannedValue, setScannedValue] = useState('')
  const [errorMsg, setErrorMsg] = useState('')
  const [searching, setSearching] = useState(false)

  async function findEquipment(rawValue: string) {
    setSearching(true)
    const supabase = createClient()

    // Try URL format first (QR codes generated by the app)
    try {
      const url = new URL(rawValue)
      const match = url.pathname.match(/\/equipment\/([^/]+)/)
      if (match) {
        setStatus('found')
        setTimeout(() => router.push(`/equipment/${match[1]}`), 600)
        return
      }
    } catch { /* not a URL */ }

    // Search by serial_no (barcode on equipment)
    const { data } = await supabase
      .from('equipment')
      .select('id, name')
      .eq('serial_no', rawValue)
      .single()

    if (data) {
      setStatus('found')
      setTimeout(() => router.push(`/equipment/${data.id}`), 600)
    } else {
      setStatus('not-found')
    }
    setSearching(false)
  }

  async function startScanner() {
    if (typeof window === 'undefined') return
    setStatus('scanning')
    setErrorMsg('')
    setScannedValue('')

    try {
      const { Html5Qrcode, Html5QrcodeSupportedFormats } = await import('html5-qrcode')

      if (scannerInstance.current) {
        try { await scannerInstance.current.stop() } catch {}
      }

      // Html5Qrcode instance supports formatsToSupport at construction time
      const formatsToSupport = [
        Html5QrcodeSupportedFormats.CODE_128,
        Html5QrcodeSupportedFormats.CODE_39,
        Html5QrcodeSupportedFormats.CODE_93,
        Html5QrcodeSupportedFormats.EAN_13,
        Html5QrcodeSupportedFormats.EAN_8,
        Html5QrcodeSupportedFormats.UPC_A,
        Html5QrcodeSupportedFormats.UPC_E,
        Html5QrcodeSupportedFormats.QR_CODE,
        Html5QrcodeSupportedFormats.DATA_MATRIX,
      ]

      const scanner = new Html5Qrcode('qr-scanner-div', { formatsToSupport, verbose: false })
      scannerInstance.current = scanner

      await scanner.start(
        { facingMode: 'environment' },
        {
          fps: 10,
          // Wider box suits 1D barcodes; still works for QR
          qrbox: { width: 280, height: 120 },
        },
        async (decodedText: string) => {
          // Stop scanning immediately on first hit
          scanner.stop().catch(() => {})
          scannerInstance.current = null
          setScannedValue(decodedText)
          await findEquipment(decodedText)
        },
        () => {} // QR not found in this frame — ignore
      )
    } catch {
      setStatus('error')
      setErrorMsg('Camera access denied or not supported on this browser')
    }
  }

  async function stopScanner() {
    if (scannerInstance.current) {
      try { await scannerInstance.current.stop() } catch {}
      scannerInstance.current = null
    }
    setStatus('idle')
  }

  useEffect(() => {
    return () => {
      if (scannerInstance.current) {
        scannerInstance.current.stop().catch(() => {})
      }
    }
  }, [])

  return (
    <div className="space-y-4">
      {/* Viewport */}
      <div className="relative card overflow-hidden">
        {/* Live camera feed */}
        <div
          id="qr-scanner-div"
          className={`w-full ${status === 'scanning' ? 'block' : 'hidden'}`}
        />

        {/* States when not scanning */}
        {status !== 'scanning' && (
          <div className="aspect-[4/3] flex flex-col items-center justify-center gap-4 bg-slate-50 dark:bg-slate-800/50 rounded-2xl px-6">
            {status === 'idle' && (
              <>
                <div className="relative">
                  <div className="absolute inset-0 bg-indigo-100 dark:bg-indigo-900/30 rounded-full animate-ping opacity-30" />
                  <div className="relative w-24 h-24 bg-indigo-50 dark:bg-indigo-900/20 rounded-full flex items-center justify-center border-2 border-dashed border-indigo-200 dark:border-indigo-700">
                    <QrCode className="w-10 h-10 text-indigo-400" />
                  </div>
                </div>
                <div className="text-center">
                  <p className="font-semibold text-slate-700 dark:text-slate-300">Ready to Scan</p>
                  <p className="text-sm text-slate-400 mt-1">Supports barcodes (Code 128, EAN) and QR codes</p>
                </div>
              </>
            )}

            {(status === 'found' || searching) && (
              <>
                {searching
                  ? <Loader2 className="w-14 h-14 text-indigo-400 animate-spin" />
                  : <CheckCircle2 className="w-14 h-14 text-emerald-500" />
                }
                <div className="text-center">
                  <p className="font-semibold text-emerald-700 dark:text-emerald-400">
                    {searching ? 'Looking up equipment...' : 'Equipment Found!'}
                  </p>
                  <p className="text-xs text-slate-400 mt-1 font-mono break-all">{scannedValue}</p>
                  {!searching && <p className="text-sm text-slate-500 mt-1">Redirecting...</p>}
                </div>
              </>
            )}

            {status === 'not-found' && (
              <>
                <Search className="w-14 h-14 text-slate-300 dark:text-slate-600" />
                <div className="text-center">
                  <p className="font-semibold text-slate-600 dark:text-slate-400">Equipment Not Found</p>
                  <p className="text-xs text-slate-400 mt-1">No equipment with serial:</p>
                  <p className="text-sm font-mono text-slate-600 dark:text-slate-300 mt-0.5 break-all">{scannedValue}</p>
                  <p className="text-xs text-slate-400 mt-2">Make sure the serial number in the system matches the barcode exactly.</p>
                </div>
              </>
            )}

            {status === 'error' && (
              <>
                <AlertCircle className="w-14 h-14 text-rose-400" />
                <div className="text-center">
                  <p className="font-semibold text-rose-600 dark:text-rose-400">Camera Error</p>
                  <p className="text-sm text-slate-400 mt-1">{errorMsg}</p>
                </div>
              </>
            )}
          </div>
        )}

        {/* Scan overlay — barcode-shaped wider rectangle */}
        {status === 'scanning' && (
          <div className="absolute inset-0 pointer-events-none flex items-center justify-center">
            <div className="relative">
              {/* Dark overlay everything EXCEPT the scan box */}
              <div className="w-72 h-28 border-2 border-white/70 rounded-xl shadow-[0_0_0_9999px_rgba(0,0,0,0.45)]">
                {/* Corner markers */}
                <div className="absolute top-0 left-0 w-6 h-6 border-t-[3px] border-l-[3px] border-indigo-400 rounded-tl-lg" />
                <div className="absolute top-0 right-0 w-6 h-6 border-t-[3px] border-r-[3px] border-indigo-400 rounded-tr-lg" />
                <div className="absolute bottom-0 left-0 w-6 h-6 border-b-[3px] border-l-[3px] border-indigo-400 rounded-bl-lg" />
                <div className="absolute bottom-0 right-0 w-6 h-6 border-b-[3px] border-r-[3px] border-indigo-400 rounded-br-lg" />
                {/* Scan line animation */}
                <div className="absolute inset-x-1 h-0.5 bg-indigo-400/70 animate-[scanLine_2s_ease-in-out_infinite]" style={{ top: '50%' }} />
              </div>
              <p className="text-white/70 text-xs text-center mt-3">Align barcode within the frame</p>
            </div>
          </div>
        )}
      </div>

      {/* Controls */}
      {status !== 'scanning' ? (
        <button onClick={startScanner} className="w-full btn-primary py-4 text-base">
          <Camera className="w-5 h-5" />
          {status === 'not-found' || status === 'error' ? 'Scan Again' : 'Open Camera & Scan'}
        </button>
      ) : (
        <button onClick={stopScanner} className="w-full btn-secondary py-4">
          Stop Camera
        </button>
      )}

      {/* Tips */}
      <div className="card p-4 space-y-1.5">
        <p className="text-xs font-semibold text-slate-600 dark:text-slate-400">Tips for scanning</p>
        <p className="text-xs text-slate-400">• Hold phone steady, 10–20 cm from barcode</p>
        <p className="text-xs text-slate-400">• Good lighting helps — avoid glare</p>
        <p className="text-xs text-slate-400">• Works with Code 128, EAN-13, QR Code and more</p>
        <p className="text-xs text-slate-400">• Serial number must match exactly what&apos;s in the system</p>
      </div>
    </div>
  )
}
