'use client'

import { useEffect, useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Camera, CheckCircle2, AlertCircle, QrCode, Search, Loader2, Package } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import { Equipment } from '@/lib/types'

type ScanStatus = 'idle' | 'scanning' | 'found' | 'not-found' | 'error'

export default function QRScannerClient() {
  const router = useRouter()
  const scannerInstance = useRef<any>(null)
  const [status, setStatus] = useState<ScanStatus>('idle')
  const [scannedValue, setScannedValue] = useState('')
  const [errorMsg, setErrorMsg] = useState('')
  const [searching, setSearching] = useState(false)

  // Manual search state
  const [query, setQuery] = useState('')
  const [manualSearching, setManualSearching] = useState(false)
  const [manualResults, setManualResults] = useState<Pick<Equipment, 'id' | 'name' | 'serial_no' | 'status'>[] | null>(null)

  async function findEquipment(rawValue: string) {
    setSearching(true)
    const supabase = createClient()

    // Try URL format first (QR codes generated by the app)
    try {
      const url = new URL(rawValue)
      const match = url.pathname.match(/\/equipment\/([^/]+)/)
      if (match) {
        setStatus('found')
        setTimeout(() => router.push(`/equipment/${match[1]}`), 600)
        return
      }
    } catch { /* not a URL */ }

    // Search by serial_no (barcode on equipment)
    const { data } = await supabase
      .from('equipment')
      .select('id, name')
      .eq('serial_no', rawValue)
      .single()

    if (data) {
      setStatus('found')
      setTimeout(() => router.push(`/equipment/${data.id}`), 600)
    } else {
      setStatus('not-found')
    }
    setSearching(false)
  }

  async function handleManualSearch() {
    const q = query.trim()
    if (!q) return
    setManualSearching(true)
    setManualResults(null)
    const supabase = createClient()
    const { data } = await supabase
      .from('equipment')
      .select('id, name, serial_no, status')
      .or(`name.ilike.%${q}%,serial_no.ilike.%${q}%`)
      .order('name')
      .limit(10)
    setManualResults(data ?? [])
    setManualSearching(false)
  }

  async function startScanner() {
    if (typeof window === 'undefined') return
    setStatus('scanning')
    setErrorMsg('')
    setScannedValue('')

    try {
      const { Html5Qrcode, Html5QrcodeSupportedFormats } = await import('html5-qrcode')

      if (scannerInstance.current) {
        try { await scannerInstance.current.stop() } catch {}
      }

      // Html5Qrcode instance supports formatsToSupport at construction time
      const formatsToSupport = [
        Html5QrcodeSupportedFormats.CODE_128,
        Html5QrcodeSupportedFormats.CODE_39,
        Html5QrcodeSupportedFormats.CODE_93,
        Html5QrcodeSupportedFormats.EAN_13,
        Html5QrcodeSupportedFormats.EAN_8,
        Html5QrcodeSupportedFormats.UPC_A,
        Html5QrcodeSupportedFormats.UPC_E,
        Html5QrcodeSupportedFormats.QR_CODE,
        Html5QrcodeSupportedFormats.DATA_MATRIX,
      ]

      const scanner = new Html5Qrcode('qr-scanner-div', { formatsToSupport, verbose: false })
      scannerInstance.current = scanner

      await scanner.start(
        { facingMode: 'environment' },
        {
          fps: 10,
          // Wider box suits 1D barcodes; still works for QR
          qrbox: { width: 280, height: 120 },
        },
        async (decodedText: string) => {
          // Stop scanning immediately on first hit
          scanner.stop().catch(() => {})
          scannerInstance.current = null
          setScannedValue(decodedText)
          await findEquipment(decodedText)
        },
        () => {} // QR not found in this frame — ignore
      )
    } catch {
      setStatus('error')
      setErrorMsg('Camera access denied or not supported on this browser')
    }
  }

  async function stopScanner() {
    if (scannerInstance.current) {
      try { await scannerInstance.current.stop() } catch {}
      scannerInstance.current = null
    }
    setStatus('idle')
  }

  useEffect(() => {
    return () => {
      if (scannerInstance.current) {
        scannerInstance.current.stop().catch(() => {})
      }
    }
  }, [])

  return (
    <div className="space-y-4">
      {/* Viewport */}
      <div className="relative card overflow-hidden">
        {/* Live camera feed */}
        <div
          id="qr-scanner-div"
          className={`w-full ${status === 'scanning' ? 'block' : 'hidden'}`}
        />

        {/* States when not scanning */}
        {status !== 'scanning' && (
          <div className="aspect-[4/3] flex flex-col items-center justify-center gap-4 bg-slate-50 dark:bg-slate-800/50 rounded-2xl px-6">
            {status === 'idle' && (
              <>
                <div className="relative">
                  <div className="absolute inset-0 bg-indigo-100 dark:bg-indigo-900/30 rounded-full animate-ping opacity-30" />
                  <div className="relative w-24 h-24 bg-indigo-50 dark:bg-indigo-900/20 rounded-full flex items-center justify-center border-2 border-dashed border-indigo-200 dark:border-indigo-700">
                    <QrCode className="w-10 h-10 text-indigo-400" />
                  </div>
                </div>
                <div className="text-center">
                  <p className="font-semibold text-slate-700 dark:text-slate-300">Ready to Scan</p>
                  <p className="text-sm text-slate-400 mt-1">Supports barcodes (Code 128, EAN) and QR codes</p>
                </div>
              </>
            )}

            {(status === 'found' || searching) && (
              <>
                {searching
                  ? <Loader2 className="w-14 h-14 text-indigo-400 animate-spin" />
                  : <CheckCircle2 className="w-14 h-14 text-emerald-500" />
                }
                <div className="text-center">
                  <p className="font-semibold text-emerald-700 dark:text-emerald-400">
                    {searching ? 'Looking up equipment...' : 'Equipment Found!'}
                  </p>
                  <p className="text-xs text-slate-400 mt-1 font-mono break-all">{scannedValue}</p>
                  {!searching && <p className="text-sm text-slate-500 mt-1">Redirecting...</p>}
                </div>
              </>
            )}

            {status === 'not-found' && (
              <>
                <Search className="w-14 h-14 text-slate-300 dark:text-slate-600" />
                <div className="text-center">
                  <p className="font-semibold text-slate-600 dark:text-slate-400">Equipment Not Found</p>
                  <p className="text-xs text-slate-400 mt-1">No equipment with serial:</p>
                  <p className="text-sm font-mono text-slate-600 dark:text-slate-300 mt-0.5 break-all">{scannedValue}</p>
                  <p className="text-xs text-slate-400 mt-2">Make sure the serial number in the system matches the barcode exactly.</p>
                </div>
              </>
            )}

            {status === 'error' && (
              <>
                <AlertCircle className="w-14 h-14 text-rose-400" />
                <div className="text-center">
                  <p className="font-semibold text-rose-600 dark:text-rose-400">Camera Error</p>
                  <p className="text-sm text-slate-400 mt-1">{errorMsg}</p>
                </div>
              </>
            )}
          </div>
        )}

        {/* Scan overlay — barcode-shaped wider rectangle */}
        {status === 'scanning' && (
          <div className="absolute inset-0 pointer-events-none flex items-center justify-center">
            <div className="relative">
              {/* Dark overlay everything EXCEPT the scan box */}
              <div className="w-72 h-28 border-2 border-white/70 rounded-xl shadow-[0_0_0_9999px_rgba(0,0,0,0.45)]">
                {/* Corner markers */}
                <div className="absolute top-0 left-0 w-6 h-6 border-t-[3px] border-l-[3px] border-indigo-400 rounded-tl-lg" />
                <div className="absolute top-0 right-0 w-6 h-6 border-t-[3px] border-r-[3px] border-indigo-400 rounded-tr-lg" />
                <div className="absolute bottom-0 left-0 w-6 h-6 border-b-[3px] border-l-[3px] border-indigo-400 rounded-bl-lg" />
                <div className="absolute bottom-0 right-0 w-6 h-6 border-b-[3px] border-r-[3px] border-indigo-400 rounded-br-lg" />
                {/* Scan line animation */}
                <div className="absolute inset-x-1 h-0.5 bg-indigo-400/70 animate-[scanLine_2s_ease-in-out_infinite]" style={{ top: '50%' }} />
              </div>
              <p className="text-white/70 text-xs text-center mt-3">Align barcode within the frame</p>
            </div>
          </div>
        )}
      </div>

      {/* Controls */}
      {status !== 'scanning' ? (
        <button onClick={startScanner} className="w-full btn-primary py-4 text-base">
          <Camera className="w-5 h-5" />
          {status === 'not-found' || status === 'error' ? 'Scan Again' : 'Open Camera & Scan'}
        </button>
      ) : (
        <button onClick={stopScanner} className="w-full btn-secondary py-4">
          Stop Camera
        </button>
      )}

      {/* Manual search */}
      <div className="space-y-3">
        <div className="flex items-center gap-3">
          <div className="flex-1 h-px bg-slate-200 dark:bg-slate-700" />
          <span className="text-xs text-slate-400 shrink-0">หรือค้นหาด้วยตัวเอง</span>
          <div className="flex-1 h-px bg-slate-200 dark:bg-slate-700" />
        </div>

        <form
          onSubmit={(e) => { e.preventDefault(); handleManualSearch() }}
          className="flex gap-2"
        >
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
            <input
              type="search"
              value={query}
              onChange={(e) => { setQuery(e.target.value); setManualResults(null) }}
              placeholder="ชื่ออุปกรณ์ หรือ Serial No."
              className="input-base pl-9"
            />
          </div>
          <button
            type="submit"
            disabled={!query.trim() || manualSearching}
            className="btn-primary px-4 shrink-0 disabled:opacity-50"
          >
            {manualSearching ? <Loader2 className="w-4 h-4 animate-spin" /> : 'ค้นหา'}
          </button>
        </form>

        {/* Search results */}
        {manualResults !== null && (
          manualResults.length === 0 ? (
            <div className="card p-6 text-center">
              <Search className="w-8 h-8 text-slate-300 dark:text-slate-600 mx-auto mb-2" />
              <p className="text-sm font-medium text-slate-500">ไม่พบอุปกรณ์</p>
              <p className="text-xs text-slate-400 mt-1">ลองค้นหาด้วยชื่อหรือ serial อื่น</p>
            </div>
          ) : (
            <div className="card divide-y divide-slate-100 dark:divide-slate-800 overflow-hidden">
              {manualResults.map((eq) => (
                <button
                  key={eq.id}
                  onClick={() => router.push(`/equipment/${eq.id}`)}
                  className="w-full flex items-center gap-3 px-4 py-3 hover:bg-slate-50 dark:hover:bg-slate-800/60 transition-colors text-left"
                >
                  <div className="w-8 h-8 rounded-lg bg-indigo-50 dark:bg-indigo-900/20 flex items-center justify-center shrink-0">
                    <Package className="w-4 h-4 text-indigo-400" />
                  </div>
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-medium text-slate-800 dark:text-slate-200 truncate">{eq.name}</p>
                    {eq.serial_no && (
                      <p className="text-xs text-slate-400 font-mono">{eq.serial_no}</p>
                    )}
                  </div>
                  <span className={`text-xs px-2 py-0.5 rounded-full font-medium shrink-0 ${
                    eq.status === 'available'
                      ? 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400'
                      : eq.status === 'borrowed' || eq.status === 'overdue'
                      ? 'bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400'
                      : 'bg-slate-100 dark:bg-slate-800 text-slate-500'
                  }`}>
                    {eq.status}
                  </span>
                </button>
              ))}
            </div>
          )
        )}
      </div>

      {/* Tips */}
      <div className="card p-4 space-y-1.5">
        <p className="text-xs font-semibold text-slate-600 dark:text-slate-400">Tips for scanning</p>
        <p className="text-xs text-slate-400">• Hold phone steady, 10–20 cm from barcode</p>
        <p className="text-xs text-slate-400">• Good lighting helps — avoid glare</p>
        <p className="text-xs text-slate-400">• Works with Code 128, EAN-13, QR Code and more</p>
        <p className="text-xs text-slate-400">• Serial number must match exactly what&apos;s in the system</p>
      </div>
    </div>
  )
}
